"use client";

import { useState } from "react";
import raw from "@/data/cards.json";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Slider } from "@/components/ui/slider";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ArrowUpRight } from "lucide-react";

type Key = "reserve" | "preferred" | "venturex" | "venture" | "gold" | "platinum" | "bilt" | "palladium";
type Info = { name: string; fee: number; subtitle: string; url: string; referralUrl?: string; welcome: { headline: string; detail: string }; perks: [string, number, string, number?][]; extras: [string, string, string][] };
const cards = raw as unknown as Record<Key, Info>;
const order: Key[] = ["reserve", "preferred", "venturex", "venture", "gold", "platinum", "bilt", "palladium"];
const label: Record<Key, string> = { reserve: "Sapphire Reserve", preferred: "Sapphire Preferred", venturex: "Venture X", venture: "Venture", gold: "Amex Gold", platinum: "Amex Platinum", bilt: "Bilt Blue", palladium: "Bilt Palladium" };
const money = (n: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n);

export default function Home() {
  const [active, setActive] = useState<Key>("reserve");
  const [values, setValues] = useState<Record<string, number>>({ "reserve-0": 300 });
  const card = cards[active];
  const total = card.perks.reduce((sum, perk, i) => sum + (values[`${active}-${i}`] ?? perk[3] ?? 0), 0);
  const difference = total - card.fee;

  return <main>
    <section className="paper-shell">
      <div className="mx-auto max-w-[1320px] px-5 sm:px-9">
        <header className="flex items-center justify-between border-b border-[#d6d4ce] py-5 text-[0.8rem]"><span className="font-bold uppercase tracking-[0.13em]">Flight points <span className="text-[#a19e98]">/</span> a friend&apos;s guide</span><span className="hidden text-[#77756f] sm:block">Public U.S. benefits · September 24, 2026</span></header>
        <div className="mx-auto max-w-[1040px] py-13 text-center sm:py-17"><p className="mb-5 text-[0.76rem] font-semibold uppercase tracking-[0.18em] text-[#77756f]">A closer look at travel card benefits</p><h1 className="editorial-title mx-auto max-w-[960px] text-[clamp(2.7rem,5.7vw,5.6rem)] leading-[1.04] tracking-[-0.052em]">What are the perks <em className="marker-underline">actually worth?</em></h1><p className="mx-auto mt-6 max-w-[640px] text-[1.04rem] leading-7 text-[#66655f]">Listed values are ceilings. Set each credit to what you would spend anyway and see what remains of the annual fee.</p></div>
      </div>
    </section>
    <section className="dark-stage dark relative min-h-screen overflow-hidden bg-[#131313] text-[#f4f2ed]"><div className="spectral-rule" aria-hidden="true"/><div className="ambient-glow" aria-hidden="true"/>
      <div className="relative mx-auto max-w-[1320px] px-5 pb-24 pt-9 sm:px-9 sm:pt-12">
        <div className="mb-7 flex flex-wrap items-end justify-between gap-5"><div><p className="mb-3 text-[0.74rem] font-semibold uppercase tracking-[0.2em] text-[#aaa9a4]">01 / Choose a card</p><h2 className="editorial-title text-[clamp(2rem,3.5vw,3.5rem)] leading-[1.1]">Compare the <span className="iridescent-text">real value.</span></h2></div><p className="max-w-[340px] text-[0.91rem] leading-6 text-[#aaa9a4]">One-time sign-up offers are shown separately from the annual credit estimate.</p></div>
        <Tabs value={active} onValueChange={(v) => setActive(v as Key)} className="gap-0"><div className="scrollbar-thin mb-8 overflow-x-auto pb-2"><TabsList variant="line" className="h-auto min-w-max justify-start gap-1 border-b border-white/12 bg-transparent p-0">{order.map((key) => <TabsTrigger key={key} value={key} className="h-11 flex-none rounded-none px-4 text-[0.88rem] font-medium text-[#aaa9a4] hover:text-white data-[state=active]:bg-transparent data-[state=active]:text-white">{label[key]}</TabsTrigger>)}</TabsList></div></Tabs>
        <div className="mb-8 grid gap-5 md:grid-cols-[1fr_auto] md:items-end"><div><p className="mb-2 text-[0.74rem] font-semibold uppercase tracking-[0.18em] text-[#aaa9a4]">02 / Benefits breakdown</p><h3 className="editorial-title text-[clamp(2rem,3.8vw,3.8rem)] leading-[1.08] tracking-[-0.045em]">{card.name}</h3><p className="mt-3 max-w-[650px] text-[0.98rem] text-[#aaa9a4]">{card.subtitle}</p></div><div className="md:text-right"><div className="text-[0.74rem] font-semibold uppercase tracking-[0.18em] text-[#aaa9a4]">Annual fee</div><div className="editorial-title mt-1 text-[2.7rem] leading-none">{money(card.fee)}</div></div></div>
        <Card className="mb-8 overflow-hidden rounded-[18px] border-[#9d80bf]/35 bg-[linear-gradient(115deg,rgba(119,84,159,.24),rgba(37,36,34,.94)_57%)] py-0 text-[#f4f2ed] shadow-none"><CardContent className="flex flex-col gap-6 p-6 sm:p-8 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><Badge variant="outline" className="mb-3 rounded-full border-[#d5b8ff]/35 text-[#e7d4ff]">One-time welcome offer</Badge><h4 className="editorial-title text-[clamp(1.6rem,2.6vw,2.6rem)] leading-tight">{card.welcome.headline}</h4><p className="mt-2 max-w-[760px] text-[0.91rem] leading-6 text-[#c4c0bb]">{card.welcome.detail}</p><p className="mt-3 text-[0.8rem] leading-5 text-[#aaa9a4]">Shown for context; points and sign-up credits are not included in the annual fee calculation. Confirm the offer and eligibility on the application page.</p></div><div className="flex shrink-0 flex-col items-start gap-2"><Button asChild className="h-11 rounded-full bg-[#e9d9ff] px-6 text-[#20162a] hover:bg-white"><a href={card.referralUrl ?? card.url} target="_blank" rel="noopener noreferrer">Get this card <ArrowUpRight className="ml-1 size-4"/></a></Button>{card.referralUrl && <span className="max-w-[240px] text-[0.76rem] leading-5 text-[#aaa9a4]">Referral link · Nathan may receive a bonus if you apply.</span>}</div></CardContent></Card>
        <div className="grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_330px]">
          <Card className="overflow-hidden rounded-[18px] border-white/14 bg-[#1d1d1c]/90 py-0 text-[#f4f2ed] shadow-none"><div className="flex justify-between border-b border-white/12 px-5 py-4 text-[0.75rem] font-semibold uppercase tracking-[0.14em] text-[#aaa9a4] sm:px-7"><span>Perk &amp; conditions</span><span>Stated value</span></div><CardContent className="p-0">{card.perks.length === 0 ? <div className="p-7"><h4 className="editorial-title text-[1.7rem]">No fixed recurring statement credit.</h4><p className="mt-2 text-[#aaa9a4]">Benefits below depend on a booking, an application, or spending.</p></div> : card.perks.map((perk, i) => { const value = values[`${active}-${i}`] ?? perk[3] ?? 0; return <div key={`${active}-${i}`} className="grid gap-5 border-b border-white/10 px-5 py-5 last:border-0 sm:grid-cols-[minmax(0,1fr)_195px] sm:px-7 sm:py-6"><div><div className="mb-2 flex flex-wrap items-center gap-2"><h4 className="text-[1.04rem] font-semibold">{perk[0]}</h4><Badge variant="outline" className="rounded-full border-white/20 px-2.5 text-[0.7rem] font-medium text-[#aaa9a4]">annual ceiling</Badge></div><p className="max-w-[600px] text-[0.91rem] leading-6 text-[#aaa9a4]">{perk[2]}</p></div><div className="sm:text-right"><div className="text-[1.1rem] font-semibold text-[#eee6fa]">Up to {money(perk[1])}</div><label htmlFor={`perk-${active}-${i}`} className="mt-3 mb-2 flex justify-between text-[0.8rem] text-[#aaa9a4] sm:justify-end sm:gap-2"><span>I&apos;d use</span><strong className="text-white">{money(value)}</strong></label><Slider id={`perk-${active}-${i}`} min={0} max={perk[1]} step={perk[1] === 84 ? 7 : perk[1] === 288 ? 24 : perk[1] % 10 === 0 ? 10 : 1} value={[value]} onValueChange={(v) => setValues((old) => ({ ...old, [`${active}-${i}`]: v[0] ?? 0 }))} aria-label={`Usable value for ${perk[0]}`} className="[&_[data-slot=slider-range]]:bg-[#d5b8ff] [&_[data-slot=slider-thumb]]:border-[#d5b8ff] [&_[data-slot=slider-track]]:bg-white/15"/></div></div>; })}</CardContent></Card>
          <Card className="rounded-[18px] border-white/18 bg-[#252422]/90 py-0 text-[#f4f2ed] shadow-[0_20px_80px_rgba(0,0,0,.16)] backdrop-blur-sm lg:sticky lg:top-6"><CardContent className="p-6 sm:p-7"><p className="mb-5 text-[0.74rem] font-semibold uppercase tracking-[0.17em] text-[#aaa9a4]">Your estimate</p><div className="iridescent-text editorial-title pb-2 text-[clamp(2.8rem,4vw,4rem)] leading-[1.15] tracking-[-0.055em]">{money(total)}</div><p className="mt-3 text-[0.92rem] leading-6 text-[#aaa9a4]">Recurring credits you would use in a full year.</p><Separator className="my-6 bg-white/13"/><div className="space-y-2 text-[0.92rem]"><div className="flex justify-between"><span className="text-[#aaa9a4]">Usable credits</span><span>{money(total)}</span></div><div className="flex justify-between"><span className="text-[#aaa9a4]">Annual fee</span><span>−{money(card.fee)}</span></div></div><Separator className="my-5 bg-white/13"/><div aria-live="polite" className="editorial-title text-[1.65rem] leading-tight">{difference >= 0 ? `${money(difference)} above the fee` : `${money(-difference)} of fee left`}</div><p className="mt-5 text-[0.81rem] leading-5 text-[#9d9c96]">Credits have eligibility rules and expiry dates. Point multipliers, lounges, and insurance limits are excluded.</p></CardContent></Card>
        </div>
        <section className="mt-18 pt-4" aria-labelledby="extra-heading"><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p className="mb-2 text-[0.74rem] font-semibold uppercase tracking-[0.18em] text-[#aaa9a4]">03 / Beyond annual credits</p><h3 id="extra-heading" className="editorial-title text-[clamp(2rem,3.5vw,3.35rem)]">Other benefits.</h3></div><span className="text-[0.88rem] text-[#aaa9a4]">One-time, conditional, or personal value</span></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{card.extras.map(([name, amount, detail]) => <Card key={name} className="rounded-[16px] border-white/12 bg-[#1d1d1c]/80 py-0 text-[#f4f2ed] shadow-none"><CardContent className="flex h-full flex-col p-6"><h4 className="font-semibold">{name}</h4><p className="editorial-title my-3 text-[1.55rem] leading-tight text-[#ddc9f6]">{amount}</p><p className="mt-auto text-[0.88rem] leading-6 text-[#aaa9a4]">{detail}</p></CardContent></Card>)}</div></section>
        <section className="mt-20" aria-labelledby="seats-heading"><div className="mb-7 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-3 text-[0.74rem] font-semibold uppercase tracking-[0.18em] text-[#aaa9a4]">04 / Redeem your points</p><h3 id="seats-heading" className="editorial-title max-w-[800px] text-[clamp(2.2rem,4vw,4rem)] leading-[1.08]">Find the seat before you <span className="iridescent-text">move the points.</span></h3></div><p className="max-w-[370px] text-[0.92rem] leading-6 text-[#aaa9a4]">Seats.aero is my go-to for comparing award flights and the points required across mileage programs. Its Live Search gives the freshest results; confirm seats and taxes with the airline before transferring points.</p></div><div className="grid gap-3 md:grid-cols-3">{[
          ["01", "Search the route", "Enter your departure city and destination, then compare dates, cabins, mileage programs, points and fees. Flexibility helps for Europe and Australia."],
          ["02", "Set an alert", "In Seats.aero, open Alerts → Create alert. Pick a route, travel date or range, cabin, and optional max points or fees. Choose a one-off alert and save it."],
          ["03", "Act on the match", "Watch for an email or app notification, verify the same flight on the airline’s site, then transfer points and book. Continuous alerts and unlimited alerts require Pro."]
        ].map(([num, title, detail]) => <Card key={num} className="rounded-[16px] border-white/12 bg-[#1d1d1c]/80 py-0 text-[#f4f2ed] shadow-none"><CardContent className="p-6"><span className="editorial-title text-[1.7rem] text-[#ddc9f6]">{num}</span><h4 className="mt-4 text-[1.12rem] font-semibold">{title}</h4><p className="mt-2 text-[0.9rem] leading-6 text-[#aaa9a4]">{detail}</p></CardContent></Card>)}</div><div className="mt-6 flex flex-wrap items-center gap-4"><Button asChild className="h-11 rounded-full bg-[#e9d9ff] px-6 text-[#20162a] hover:bg-white"><a href="https://seats.aero/r/iggospcb" target="_blank" rel="noopener noreferrer">Explore Seats.aero <ArrowUpRight className="ml-1 size-4"/></a></Button><a href="https://docs.seats.aero/article/43-creating-and-managing-alerts" target="_blank" rel="noopener noreferrer" className="text-[0.87rem] text-[#d5b8ff] underline underline-offset-4 hover:text-white">Alert instructions</a><p className="basis-full text-[0.79rem] leading-5 text-[#aaa9a4]">The Seats.aero button is Nathan’s referral link. The free tier currently allows up to five active alerts; search results and award seats can change before you book.</p></div></section>
        <div className="mt-14 flex flex-col items-start justify-between gap-5 border-t border-white/13 pt-7 sm:flex-row sm:items-center"><p className="max-w-[760px] text-[0.83rem] leading-6 text-[#aaa9a4]">Values are maximums, not guaranteed savings. Some require enrollment or expire monthly. Compare the issuer terms with any offer displayed through a referral link.</p><Button variant="outline" asChild className="rounded-full border-white/25 bg-transparent px-5 text-white hover:border-white/50 hover:bg-white/8 hover:text-white"><a href={card.url} target="_blank" rel="noopener noreferrer">Official card terms <ArrowUpRight className="ml-1 size-4"/></a></Button></div>
        <footer className="mt-16 flex flex-wrap justify-between gap-3 text-[0.78rem] text-[#85847f]"><span>Flight points / a friend&apos;s guide</span><span>Reviewed September 24, 2026</span></footer>
      </div>
    </section>
  </main>;
}
